services:
  database:
    image: mysql:8
    container_name: sgu-database-https
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu
      MYSQL_USER: sgu_user
      MYSQL_PASSWORD: sgu_password
    ports:
      - "3308:3306"
    volumes:
      - sgu-volume-https:/var/lib/mysql
    networks:
      - sgu-net-https
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_HOST: localhost
        VITE_API_PORT: 8444
        VITE_API_BASE: /sgu-api
    image: client:1.0-sgu-https
    container_name: sgu-frontend-https
    ports:
      - "3001:443"
      - "3002:80"
    networks:
      - sgu-net-https
    depends_on:
      database:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: server:1.0-sgu-https
    container_name: sgu-backend-https
    environment:
      DB_URL: jdbc:mysql://database:3306/sgu
      DB_USER: sgu_user
      DB_PASS: sgu_password
    ports:
      - "8444:8443"
    networks:
      - sgu-net-https
    depends_on:
      database:
        condition: service_healthy

networks:
  sgu-net-https:
    driver: bridge

volumes:
  sgu-volume-https:
    external: false
